### ISSUE TITLE
drawing a line creates perpetual loading 

### ISSUE THREAD

**Issue by sidewalkballet** [esridc/CensusIQ#1]
1. draw a line
2. see it never load 

maybe should prompt the user to draw a polygon, or not let a line be drawn (user has to have at least three vertices)

<img width="1527" alt="screen shot 2015-08-21 at 4 35 40 pm" src="https://cloud.githubusercontent.com/assets/3474250/9418536/cf661446-4822-11e5-9f69-6713f78c511a.png">

**Comment by benheb** [comment]
Crazy that it doesn't work to draw a line. Blarg. Added an alert, and insist they draw a polygon with three or more sides...
