### ISSUE TITLE
attributes are listed multiple times in the side panel

### ISSUE THREAD

**Issue by sidewalkballet** [esridc/CensusIQ#10]
STR
1. draw an area that will have multiple polygons in it 
2. after the table loads, scroll down. see that the attribute listed is repeated multiple times. 
3. at the bottom, see multiple Selection Summary strings
<img width="1554" alt="screen shot 2015-08-25 at 9 57 32 am" src="https://cloud.githubusercontent.com/assets/3474250/9468498/02db80e6-4b10-11e5-9ccb-0d7f7ed23645.png">

**Comment by benheb** [comment]
Fixed, I think
