### ISSUE TITLE
User can but should not be able to click on an individual polygon outside the selected area 

### ISSUE THREAD

**Issue by sidewalkballet** [esridc/CensusIQ#12]
STR
1. select an area
2. click a polygon outside the area
3. see the loader try to load, nothing happens until you move your mouse, then the stats for the selected area appear again
![censusiq](https://cloud.githubusercontent.com/assets/3474250/9533158/1afbbd4c-4cde-11e5-94d4-6711ff40b3ee.gif)

**Comment by benheb** [comment]
Fixed.
