### ISSUE TITLE
link out to dataset 

### ISSUE THREAD

**Issue by sidewalkballet** [esridc/CensusIQ#5]
I might want to download this particular dataset, or explore it more. Linking to the dataset on the open data site in some way would be good. Whether an icon or something else.

**Comment by benheb** [comment]
To the open data site? Is that live yet?

**Comment by sidewalkballet** [comment]
@benheb not public, but all the data is on here: data.censusbeta.opendata.arcgis.com

**Comment by benheb** [comment]
Done. :dancers:
